version: '3'

services:
  yapi_mongo:
    image: mingming20200202/yapi_mongo
    container_name: yapi_mongo
    ports:
      - "12308:27017"
    volumes:
      - /data/db:/data/db
    privileged: true
    restart: always
    command: --auth

  yapi:
    image: mingming20200202/yapi
    container_name: yapi
    ports:
      - "12310:12310"
      - "9090:9090"
    restart: always
    links:
      - yapi_mongo
    command: bash -c "cd my-yapi/vendors && npm run install-server && cd .. && rm -rf init.lock && bash start.sh"
    depends_on:
      - yapi_mongo

  mysql_dev:
    image: mingming20200202/mysql_dev
    container_name: mysql_dev
    ports:
      - "12306:3306"
    restart: always